const canvas=document.querySelector('#arena');
const ctx=canvas.getContext('2d');
let W=0,H=0,selected=0,game=null;
const FOV=Math.PI/3, MAP=[
  '1111111111111111','1000000000000001','1011110111110101','1000010100010001',
  '1011010101011101','1001000101000001','1101011101011101','1001000001000001',
  '1011110111110101','1000000000000001','1111111111111111'];
const operators=[
 {name:'MARA VOSS',role:'BREACH',icon:'◈',gadget:'BREACH CHARGE',desc:'Opens reinforced surfaces with controlled force.'},
 {name:'ELI KESTREL',role:'RECON',icon:'⌁',gadget:'SPECTRAL DRONE',desc:'Reveals hostile positions through a remote scout.'},
 {name:'ORIN VALE',role:'SUPPORT',icon:'✚',gadget:'BARRIER FOAM',desc:'Deploys temporary ballistic cover.'},
 {name:'NYX CALDER',role:'CONTROL',icon:'◉',gadget:'SHOCK MINE',desc:'Slows and disrupts hostiles nearby.'}
];
const list=document.querySelector('#operator-list');
operators.forEach((o,i)=>{const el=document.createElement('div');el.className='op-card'+(!i?' selected':'');el.innerHTML=`<div class="op-avatar">${o.icon}</div><div><b>${o.name}</b><small>${o.desc}</small></div><span class="role">${o.role}</span>`;el.onclick=()=>{selected=i;document.querySelectorAll('.op-card').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')};list.appendChild(el)});
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=innerWidth;H=innerHeight}addEventListener('resize',resize);resize();
const keys={};let mouseDown=false;
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key==='Escape'&&game&&!game.over)document.querySelector('#pause').classList.toggle('hidden');if(e.key.toLowerCase()==='r'&&game)reload();if(e.code==='Space'&&game)gadget()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('click',()=>{if(game&&!game.over){canvas.requestPointerLock?.();shoot()}});addEventListener('mousedown',()=>mouseDown=true);addEventListener('mouseup',()=>mouseDown=false);addEventListener('mousemove',e=>{if(game&&document.pointerLockElement===canvas)game.angle+=e.movementX*.0025});
document.querySelector('#deploy').onclick=start;document.querySelector('#again').onclick=start;document.querySelector('#resume').onclick=()=>document.querySelector('#pause').classList.add('hidden');document.querySelector('#return-menu').onclick=()=>{game=null;document.querySelector('#pause').classList.add('hidden');document.querySelector('#game').classList.add('hidden');document.querySelector('#menu').classList.remove('hidden')};
function start(){document.querySelector('#menu').classList.add('hidden');document.querySelector('#game').classList.remove('hidden');document.querySelector('#result').classList.add('hidden');game={x:2.2,y:1.8,angle:0.1,hp:100,ammo:30,reserve:180,charges:2,time:300,shot:0,kills:0,over:false,last:performance.now(),enemies:makeEnemies(),gadget:operators[selected].gadget};ui();toast('CLICK THE ARENA TO CAPTURE YOUR MOUSE // CLEAR THE VAULT');requestAnimationFrame(loop)}
function makeEnemies(){return [{x:13.3,y:1.7,hp:100,alive:true},{x:12.5,y:7.7,hp:100,alive:true},{x:6.5,y:9.2,hp:100,alive:true},{x:3.2,y:6.5,hp:100,alive:true},{x:10.8,y:5.3,hp:100,alive:true}]}function wall(x,y){return y<0||y>=MAP.length||x<0||x>=MAP[0].length||MAP[Math.floor(y)][Math.floor(x)]==='1'}function blocked(x,y){return wall(x,y)}
function loop(t){if(!game)return;const dt=Math.min(.05,(t-game.last)/1000);game.last=t;if(!document.querySelector('#pause').classList.contains('hidden')){requestAnimationFrame(loop);return}if(!game.over){update(dt);render()}requestAnimationFrame(loop)}
function update(dt){game.time-=dt;game.shot-=dt;if(game.time<=0)return end(false);let speed=keys.shift?3.4:2.4,forward=(keys.w?1:0)-(keys.s?1:0),side=(keys.d?1:0)-(keys.a?1:0);let dx=(Math.cos(game.angle)*forward-Math.sin(game.angle)*side)*speed*dt,dy=(Math.sin(game.angle)*forward+Math.cos(game.angle)*side)*speed*dt;if(!blocked(game.x+dx,game.y))game.x+=dx;if(!blocked(game.x,game.y+dy))game.y+=dy;if(mouseDown)shoot();game.enemies.forEach(e=>{if(!e.alive)return;const d=Math.hypot(e.x-game.x,e.y-game.y);e.cool=(e.cool||Math.random())-dt;if(d<7&&e.cool<0){e.cool=1.5;if(Math.random()<.3){game.hp-=10;ui();if(game.hp<=0)end(false)}}});if(game.enemies.every(e=>!e.alive))end(true);document.querySelector('#clock').textContent=`${String(Math.max(0,Math.floor(game.time/60))).padStart(2,'0')}:${String(Math.max(0,Math.floor(game.time%60))).padStart(2,'0')}`}
function cast(angle){let d=0;while(d<20){d+=.03;if(wall(game.x+Math.cos(angle)*d,game.y+Math.sin(angle)*d))return d}return 20}
function shoot(){if(!game||game.over||game.shot>0||game.ammo<=0)return;game.ammo--;game.shot=.16;let best=null,bd=99;game.enemies.forEach(e=>{if(!e.alive)return;let dx=e.x-game.x,dy=e.y-game.y,d=Math.hypot(dx,dy),diff=Math.atan2(Math.sin(Math.atan2(dy,dx)-game.angle),Math.cos(Math.atan2(dy,dx)));if(Math.abs(diff)<.075&&d<cast(game.angle)+.2&&d<12&&d<bd){best=e;bd=d}});if(best){best.hp-=50;if(best.hp<=0){best.alive=false;game.kills++;toast('TARGET NEUTRALIZED')}}ui()}
function reload(){if(!game||game.ammo>=30||!game.reserve)return;const n=Math.min(30-game.ammo,game.reserve);game.ammo+=n;game.reserve-=n;ui();toast('RELOADING // READY')}
function gadget(){if(!game||!game.charges)return;game.charges--;game.enemies.forEach(e=>{if(e.alive&&Math.hypot(e.x-game.x,e.y-game.y)<2.5)e.hp-=60});toast(`${game.gadget} DEPLOYED`);ui()}
function ui(){if(!game)return;document.querySelector('#health-value').textContent=Math.max(0,game.hp);document.querySelector('#health-bar').style.width=Math.max(0,game.hp)+'%';document.querySelector('#ammo').textContent=`${game.ammo} / ${game.reserve}`;document.querySelector('#gadget-name').textContent=game.gadget;document.querySelector('#charges').textContent=game.charges?'● '.repeat(game.charges):'—'}
function toast(s){const el=document.querySelector('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function end(win){if(!game||game.over)return;game.over=true;document.exitPointerLock?.();document.querySelector('#result').classList.remove('hidden');document.querySelector('#result-title').textContent=win?'VAULT SECURED':'OPERATION LOST';document.querySelector('#result-copy').textContent=win?`${game.kills} hostile operators neutralized. The data vault is under control.`:'Your squad was eliminated before the objective was secured.'}
function render(){ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,H/2);sky.addColorStop(0,'#071016');sky.addColorStop(1,'#26343a');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H/2);ctx.fillStyle='#131b1d';ctx.fillRect(0,H/2,W,H/2);ctx.strokeStyle='#263337';for(let y=H/2;y<H;y+=35){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const z=[];for(let x=0;x<W;x+=2){const a=game.angle-FOV/2+(x/W)*FOV,d=cast(a)*Math.cos(a-game.angle),h=Math.min(H*2,H/(d*.75)),shade=Math.max(25,190-d*18);ctx.fillStyle=`rgb(${shade*.55},${shade*.72},${shade*.75})`;ctx.fillRect(x,(H-h)/2,2,h);z[x]=d}game.enemies.filter(e=>e.alive).map(e=>({e,d:Math.hypot(e.x-game.x,e.y-game.y)})).sort((a,b)=>b.d-a.d).forEach(({e,d})=>{const ang=Math.atan2(e.y-game.y,e.x-game.x);let diff=Math.atan2(Math.sin(ang-game.angle),Math.cos(ang-game.angle));if(Math.abs(diff)>FOV/2+.2)return;const sx=W/2+diff/FOV*W, size=Math.min(H*1.2,H/(d*.75)),col=Math.max(0,Math.floor(sx));if(z[col]&&d>z[col]+.2)return;ctx.fillStyle='#0b1113';ctx.fillRect(sx-size*.23,(H-size)/2,size*.46,size);ctx.fillStyle='#ff5e67';ctx.beginPath();ctx.arc(sx,(H-size)/2+size*.16,size*.14,0,7);ctx.fill();ctx.fillStyle='#ff5e67';ctx.fillRect(sx-size*.25,(H-size)/2-10,size*.5,4);ctx.fillStyle='#66e6dd';ctx.fillRect(sx-size*.25,(H-size)/2-10,size*.5*(e.hp/100),4)});ctx.strokeStyle='#66e6dd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(W/2-10,H/2);ctx.lineTo(W/2+10,H/2);ctx.moveTo(W/2,H/2-10);ctx.lineTo(W/2,H/2+10);ctx.stroke()}
